# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  registryName: lqeczigowl7uqwthreg.azurecr.io
  repositoryName: "wth/dotnetcoreapp"
  dockerFolderPath: "Application/src/RazorPagesTestSample"
  tag: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
    paths:
    - '/Application'
  pull_request:
    branches: [ "main" ]
    paths:
    - '/Application'

jobs:
  build:
    defaults:
      run:
        working-directory: "/Application/src/Razor-Pages-Test-Sample"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Auth
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: azure/docker-login@v1
    -  run: docker login $registryName -u ACR_USERNAME -p ACR_PASSWORD

    - name: Docker Build
      uses: azure/docker-login@v1
    -  run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

    - name: Docker Push
      uses: azure/docker-login@v1
    -  run: docker push $registryName/$repositoryName:$tag
      



  
